version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ~/.config/gcloud:/root/.config/gcloud:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PUSHOVER_USER_KEY=${PUSHOVER_USER_KEY}
      - PUSHOVER_APP_TOKEN=${PUSHOVER_APP_TOKEN}
    depends_on:
      - chroma
    networks:
      - default

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_db_docker:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    networks:
      - default

  cron:
    image: alpine:latest
    command: >
      sh -c "
        apk add --no-cache curl &&
        echo '*/15 * * * * curl -s -X POST http://app:8000/nintendo/monitor/start >> /var/log/nintendo_monitor.log 2>&1' > /etc/crontabs/root &&
        touch /var/log/nintendo_monitor.log &&
        crond -f -l 2
      "
    depends_on:
      - app
    volumes:
      - ./logs:/var/log
    networks:
      - default

networks:
  default:
    driver: bridge
