services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - chroma
  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_db_docker:/chroma/chroma
